### ISSUE TITLE
SFWRENG 4G06 Lecture - Sep 19, 2023

### ISSUE THREAD

**Issue by songc120** [wangq131/4G06CapstoneProjectT5#11]
## SFWRENG  4G06 Lecture
- **Date**: 2023/09/19
- **Time**: 12:30 - 13:20
-  **Location**: In person, ITB AB102
- **Attendees**: 

	- [x] @wangq131 (Qianni Wang)
	- [x] @qinj15 (Jingyao Qin)
	- [x] @shis20 (Shuting Shi)
	- [x] @songc12 (Chenwei Song)
	- [x] @gaoq20 (Qiang Gao)

**Comment by qinj15** [comment]
All team members attended the lecture.
