### ISSUE TITLE
Team 01 VnV Plan Review: Missing Traceability Matrices

### ISSUE THREAD

**Issue by r-yeh** [wangq131/4G06CapstoneProjectT5#142]
Marking TA: @CSchank 

Your VnV Plan appears to be missing the traceability matrices in Section 4.3:

![image](https://github.com/wangq131/4G06CapstoneProjectT5/assets/67233377/8e504543-ff99-43cb-a9cd-72a422a88727)

Having the traceability matrices are very important for development and testing and help to visually show that you're actually verifying and validating all your requirements. Ideally, the matrix should visually show that for all your requirements that are in scope, you should have some sort of test that meets those criteria for both FR and NFR. It would help both your team ensure that requirements are met but could also be proof for stakeholders as well that testing is complete.

**Comment by katrina799** [comment]
Hi, it seems like there is a mistake of the Vnv we uploaded when copying over from Overleaf, it seems we copied the wrong version.

We are trying to fix it right now! The Traceability Matrix will be up soon! Sorry for the inconvenience!
