### ISSUE TITLE
(Cancelled) Create a workflow to ensure an issue will have labels and the proper project linked

### ISSUE THREAD

**Issue by katrina799** [wangq131/4G06CapstoneProjectT5#15]
## Summary
- This issue is creating  a workflow to ensure an issue will have labels, assignees, and the proper project linked

## Deadline
- 09/25/2023

**Comment by qinj15** [comment]
After investigation, it is not possible to add action in the CI workflow to give the issue creator a remind message on UI after validation failure, decided to remove this issue.
