### ISSUE TITLE
Modify survey to include more data

### ISSUE THREAD

**Issue by katrina799** [wangq131/4G06CapstoneProjectT5#164]
## Summary
- Modify the survey to collect data about the program and if the course is complimentary or compulsory, 

## Deadline
- 25/11/2023

## Estimated Work Hours
- 1 hr

**Comment by qinj15** [comment]
The survey for Priority Data is updated. https://docs.google.com/forms/d/e/1FAIpQLSfhOtVjatRRG_lQ9CZGe9XF_SdITx0NZ-0U0Q0bzj6Fau-GZg/viewform?usp=sharing
