### ISSUE TITLE
Problem Statement and Goals Brainstorm Area

### ISSUE THREAD

**Issue by katrina799** [wangq131/4G06CapstoneProjectT5#21]
## Summary
- This issue is about recording ideas/discussion on project's problem statement and goals

**Comment by shis20** [comment]
**Who does this problem impact?**

 - Students in various levels of education, from high school to college institutions, have an overwhelming volume of schoolwork. 

 - Teachers and institutions who seek success and foster management skills of the student 

**What is the impact of the problem we are trying to solve?**

 - Significant consequences on students' academic performance and mental health.

**When this problem can occur?**

 - Persistent concern for students throughout the academic period, when navigating multiple courses, assignments, and exams. Peak usage can occur during midterms and finals.

**Where people are experiencing this problem?**

 - Our target users are not constrained by demography or institution type and can be anywhere worldwide.

**Why is solving this problem very important?**

 - By addressing this issue, we can improve students' learning experiences, reduce academic stress, and enhance their prospects.

**How can this problem be solved?**

 - The development of this comprehensive application combines automated task generation, intelligent task prioritization, progress visualization, calendar integration, time usage prediction, collaborative studying, facial recognition, and flexible task modification.

 - The solution should encompass a user-friendly website and mobile app, a centralized database, a social networking feature, and a well-structured training pipeline for machine learning algorithms. By providing students with the tools and resources they need to manage their time and tasks efficiently, we can empower them to succeed academically while maintaining their well-being.


Reference from A. (n.d.). Build a Better Problem Statement for Software Development. https://blog.teamairship.com/build-a-better-problem-statement
