### ISSUE TITLE
T5 Meeting 01 - Sep 25, 2023

### ISSUE THREAD

**Issue by shis20** [wangq131/4G06CapstoneProjectT5#34]
## T5 Meeting 01 Info
- **Date**: 2023/09/25
- **Time**: 16:00 - 17:00
-  **Location**: Virtual, via Teams
- **Attendees**: 

	- [x] @wangq131 (Qianni Wang)
	- [x] @qinj15 (Jingyao Qin)
	- [x] @shis20 (Shuting Shi)
	- [x] @songc12 (Chenwei Song)
	- [x] @gaoq20 (Qiang Gao)

- **Meeting Lead**: @qinj15 
- **Scribe**: @shis20 

## Agenda
- Discuss the new project design 

## Actions

* @songc120 @qinj15 @gaoq20 @wangq131 @shis20  to address issue #32 

## Meeting notes

**Brainstorming for project design**

- Xiaohongshu: Online shopping and social platforms (Instagram)

- Application for generating dance according to music  

- IOS message with extension (identify spam)  — problem with privacy

- Chatbox existing product: Microsoft generates checkboxes semi-auto customize anwsers chatbox(Power virtual agent)

- Integrated social media platform which can automatically respond (need permission)

- Facial emotion detection project (deep learning CNN)

**Study Plan App** (Potential Project Choice*)
 - Extract from the course outline pdf and generate a to-do list in an application
 - The trained AI model can prioritize tasks and sort according to the outline. (AI-based)
 - Synchronize the event/schedule to other applications(outlook/Google Calendar) Create a daily study plan according to the user’s ability or preference

 - Input: course outline pdf(hours estimated needed per week for each courses), daily routine schedule, task progress update
 - Output: build a study plan to help users increase their study efficiency and manage study work
(different views: board view (can drag time zone)/ daily checklist calendar)

**Comment by qinj15** [comment]
The issue is ready to be closed
