### ISSUE TITLE
Create Project Selection Pull Request for T5 in Dr. Smith's capston repo

### ISSUE THREAD

**Issue by qinj15** [wangq131/4G06CapstoneProjectT5#37]
## Summary
- update the project selection, project description, supervisor info in the course capstone.

## Deadline
- 09/27/2023

**Comment by gaoq20** [comment]
![image](https://github.com/wangq131/4G06CapstoneProjectT5/assets/73687717/6f64c613-ddc3-4319-8936-507bf15e217b)
