### ISSUE TITLE
Allow collaborators change settings in repo

### ISSUE THREAD

**Issue by qinj15** [wangq131/4G06CapstoneProjectT5#8]
## Summary
- Change access in the repo's settings to allow team members to manage settings

## Deadline
- 09/22/2023

**Comment by katrina799** [comment]
It seems repo owned by a personal account cannot modify the access to allow collaborators to change settings..
<img width="758" alt="Screen Shot 2023-09-17 at 7 29 42 PM" src="https://github.com/wangq131/4G06CapstoneProjectT5/assets/86222533/b753db1d-00d1-4013-83c0-d715afd7f25e">
