### ISSUE TITLE
Team 01 Unable to Add Labels

### ISSUE THREAD

**Issue by r-yeh** [wangq131/4G06CapstoneProjectT5#95]
Marking TA: @CSchank 

We seem to not have permission to add the review label to our SRS reviews. Would you be able to add one of us as a collaborator or give us permissions some other way so that we can label things properly? Alternatively, would anyone on Team 5 be able to add labels to our reviews?

**Comment by katrina799** [comment]
Hi, 
I've added labels for those SRS reviews, I'm sorry about the inconvenience, and yeah I could add one of you as a collaborator in case things like this happen, would you please provide me with an email of the member that you want me to add? Thanks!

**Comment by r-yeh** [comment]
Thank you! I think you should just be able to use my Github username `r-yeh` to add me as a collaborator. Otherwise, you can use `r.yeh2008@gmail.com`

**Comment by katrina799** [comment]
Done :)
